# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOS_Calendar' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'FSCalendar', '~> 2.8'

  # Pods for IOS_Calendar

end
